name: Running the server and Checking the Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: run fastapi server
      run: |
           python -m uvicorn main:app --reload
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
